### ISSUE TITLE
브랜치 체크아웃

### ISSUE THREAD

**Issue by misolab** [misolab/olido#7]
## master 커밋 금지!!
앞으로는 commit / push 후 PR 요청해주세요
- @jhjhj0366 : backend는 `admin/back`을 이용
- @jeong-suhwan : frontend는 `admin/front` 를 이용

체크아웃 결과는 coment로 
두분 중 마지막은 close issue

**Comment by jeong-suhwan** [comment]
로컬 브랜치로 체크아웃 완료했습니다 ~~~

**Comment by jhjhj0366** [comment]
로컬 브랜치 체크아웃 완료
